Shop.Web/Models/AD.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;

namespace Shop.Web.Models
{
    public class AD
    {
        [Key]
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        [AllowNull]
        public string Thumbnail { get; set; } = string.Empty;
        [AllowNull]
        [NotMapped]
        public IFormFile formFile { get; set; } = null;
        public DateTime ExpireTime { get; set; }
        public DateTime Created { get; set; } = DateTime.Now;
        
        public Category Category { get; set; }
    }
}
    

Shop.Web/Areas/Admin/Controllers/ADsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shop.Web.Data;
using Shop.Web.Data.Services.Interfaces;
using Shop.Web.Models;

namespace Shop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ADsController : Controller
    {
        private readonly ShopDBContext _context;
        public IServerSideService _service;

        public ADsController(ShopDBContext context,IServerSideService service)
        {
            _context = context;
            _service = service;
        }

        // GET: Admin/ADs
        public async Task<IActionResult> Index()
        {
            var shopDBContext = _context.ADs.Include(a => a.Category);
            return View(await shopDBContext.ToListAsync());
        }

        // GET: Admin/ADs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ADs == null)
            {
                return NotFound();
            }

            var aD = await _context.ADs
                .Include(a => a.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aD == null)
            {
                return NotFound();
            }

            return View(aD);
        }

        // GET: Admin/ADs/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }

        // POST: Admin/ADs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AD aD)
        {
            var image = "ad";
            if (aD.formFile.Length > 0)
            {
                image = await _service.UploadFile(aD.formFile,@"Images\Ads\");
            }
            aD.Thumbnail = image;
            _context.Add(aD);
            await _context.SaveChangesAsync();
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", aD.CategoryId);
            return RedirectToAction(nameof(Index));
        }

        // GET: Admin/ADs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null || _context.ADs == null)
            {
                return NotFound();
            }
            var aD = await _context.ADs.FindAsync(id);
            if (aD == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", aD.CategoryId);
            return View(aD);
        }

        // POST: Admin/ADs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, AD aD)
        {
            if (id != aD.Id)
            {
                return NotFound();
            }

            try
            {
                var existingAd = _context.ADs.FirstOrDefault(p => p.Id == id);

                if (existingAd == null)
                {
                    return NotFound();
                }

                var image = "";
                if (aD.Thumbnail != null && aD.Thumbnail.Length > 0)
                {
                    if (!string.IsNullOrEmpty(existingAd.Thumbnail))
                    {
                        _service.DeleteFile(@"Images\Ads\" + existingAd.Thumbnail);
                    }
                    image = await _service.UploadFile(aD.formFile, @"Images\Ads\");
                }
                existingAd.Title = aD.Title;
                existingAd.URL = aD.URL;
                existingAd.Thumbnail = image == "" ? existingAd.Thumbnail : image;
                existingAd.ExpireTime = aD.ExpireTime;

                _context.Update(existingAd);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ADExists(aD.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", aD.CategoryId);
            return RedirectToAction(nameof(Index));

        }

        // GET: Admin/ADs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ADs == null)
            {
                return NotFound();
            }

            var aD = await _context.ADs
                .Include(a => a.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aD == null)
            {
                return NotFound();
            }

            return View(aD);
        }

        // POST: Admin/ADs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ADs == null)
            {
                return Problem("Entity set 'ShopDBContext.ADs'  is null.");
            }
            var aD = await _context.ADs.FindAsync(id);
            if (aD != null)
            {
                _service.DeleteFile(@"Images\Ads\" + aD.Thumbnail);
                _context.ADs.Remove(aD);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ADExists(int id)
        {
            return (_context.ADs?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Shop.Web/Areas/Admin/Views/ADs/Create.cshtml
@model AD

<div class="row p-4">
    <div class="col-md-12">
        <h4>لیست تبلیغ ها :</h4><br />
        <hr />
    </div>
    <div class="col-md-12">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">دسته بندی</label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label class="control-label">عنوان</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">آدرس تبلیغ</label>
                <input asp-for="URL" class="form-control" />
                <span asp-validation-for="URL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">عکس</label>
                <input asp-for="formFile" class="form-control" />
                <span asp-validation-for="formFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">تاریخ انقضا</label>
                <input asp-for="ExpireTime" class="form-control" />
                <span asp-validation-for="ExpireTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="ثبت تبلیغ جدید" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Shop.Web/Areas/Admin/Views/ADs/Delete.cshtml
@model Shop.Web.Models.AD

<div class="p-4">
    <h3>Are you sure you want to delete this?</h3>
    <h4>AD</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.URL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.URL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thumbnail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thumbnail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpireTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpireTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Shop.Web/Areas/Admin/Views/ADs/Details.cshtml
@model Shop.Web.Models.AD

<div class="p-4">
    <h4>AD</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.URL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.URL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thumbnail)
        </dt>
        <dd class = "col-sm-10">
            <img src="~/Uploads/Images/Ads/@Html.DisplayFor(model => model.Thumbnail)" width="200px" height="150px" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpireTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpireTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
    <div>
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
</div>

Shop.Web/Areas/Admin/Views/ADs/Edit.cshtml
@model AD

<div class="row p-4">
    <div class="col-md-12">
        <h4>AD</h4>
        <hr />
    </div>
    <div class="col-md-12">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" value="@Model.Id" />
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="URL" class="control-label"></label>
                <input asp-for="URL" class="form-control" />
                <span asp-validation-for="URL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="formFile" class="control-label"></label>
                <input asp-for="formFile" class="form-control" />
                <span asp-validation-for="formFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <img width="300px" height="200px" src="~/Uploads/Images/Ads/@Model.Thumbnail" />
            </div>
            <div class="form-group">
                <label asp-for="ExpireTime" class="control-label"></label>
                <input asp-for="ExpireTime" class="form-control" />
                <span asp-validation-for="ExpireTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Shop.Web/Areas/Admin/Views/ADs/Index.cshtml
@model IEnumerable<AD>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">تمامی تبلیغات ها</h3><br />
                    <a asp-controller="ADs" asp-action="Create" type="button" class="btn btn-success text-light float-right"><i class="fa fa-plus"></i> اضافه کردن تبلیغ جدید</a>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="ADs" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>نام تبلیغ</th>
                                <th>عکس</th>
                                <th>دسته بندی</th>
                                <th>تاریخ انقضا</th>
                                <th>آدرس سایت</th>
                                <th>اقدامات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var AD in Model){
                                <tr>
                                    <td>@AD.Id</td>
                                    <td>@AD.Title</td>
                                    <td>
                                        <img width="150px" src="~/Uploads/Images/ADs/@AD.Thumbnail" />
                                    </td>
                                    <td>@AD.Category.Name</td>
                                    <td>@AD.ExpireTime</td>
                                    <td>@AD.URL</td>
                                    <td class="btn-group">
                                        <a asp-controller="ADs" asp-action="Details" asp-route-id="@AD.Id" class="btn btn-info">نمایش</a>
                                        <a asp-controller="ADs" asp-action="Edit" asp-route-id="@AD.Id" class="btn btn-warning">ویرایش</a>
                                        <a asp-controller="ADs" asp-action="Delete" asp-route-id="@AD.Id" class="btn btn-danger">حذف</a>
                                    </td>
                                </tr>
                            }
                            @if(Model.Count() == 0){
                                <tr>
                                    <td>یافت نشد</td>
                                    <td>یافت نشد</td>
                                    <td>
                                        <img src="~/Uploads/Images/ADs/" />
                                    </td>
                                    <td>یافت نشد</td>
                                    <td>یافت نشد</td>
                                    <td>یافت نشد</td>
                                    <td class="btn-group">
                                        <a class="btn btn-info">یافت نشد</a>
                                        <a class="btn btn-warning">یافت نشد</a>
                                        <a class="btn btn-danger">یافت نشد</a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                        <tfoot>
                            <tr>
                                <th>#</th>
                                <th>نام تبلیغ</th>
                                <th>عکس</th>
                                <th>دسته بندی</th>
                                <th>تاریخ انقضا</th>
                                <th>آدرس سایت</th>
                                <th>اقدامات</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
@section Scripts{
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables -->
    <script src="~/plugins/datatables/jquery.dataTables.js"></script>
    <script src="~/plugins/datatables/dataTables.bootstrap4.js"></script>
    <!-- SlimScroll -->
    <script src="~/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src=".~/dist/js/demo.js"></script>
    <!-- page script -->
    <script>
        $(function () {
            $("#ADs").DataTable({
                "language": {
                    "paginate": {
                        "next": "بعدی",
                        "previous": "قبلی"
                    }
                },
                "info": false,
            });
        });
    </script>
}