Shop.Web/Models/Report.cs
using System.ComponentModel.DataAnnotations;

namespace Shop.Web.Models
{
    public class Report
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public int UserId { get; set; }
        public bool IsFinally { get; set; } = false;
        public User User { get; set; }
        public ICollection<ReportMessage> ReportMessages { get; set; }
    }
}

Shop.Web/Areas/Admin/Controllers/ReportController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shop.Web.Data;
using Shop.Web.Models;

namespace Shop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ReportController : Controller
    {
        public ShopDBContext ShopDBContext { get; set; }
        private INotyfService _toastNotification { get; set; }

        public ReportController(ShopDBContext shopDBContext,INotyfService notyfService)
        {
            ShopDBContext = shopDBContext;
            _toastNotification = notyfService;
        }
        public IActionResult Index()
        {
            var reports = ShopDBContext.Reports.Where(r => r.IsFinally == false).Include(r => r.User).Include(r => r.ReportMessages);
            return View(reports);
        }

        public IActionResult Show(int Id)
        {
            var report = ShopDBContext.Reports.Include(r => r.ReportMessages).ThenInclude(rm => rm.User).FirstOrDefault(r => r.Id == Id);
            if (report == null)
            {
                return NotFound();
            }
            return View(report);
        }

        public IActionResult Close(int Id)
        {
            var report = ShopDBContext.Reports.FirstOrDefault(r => r.Id == Id);
            if (report == null)
            {
                return NotFound();
            }
            report.IsFinally = true;
            ShopDBContext.Reports.Update(report);
            ShopDBContext.SaveChanges();
            _toastNotification.Warning("ریپورت به درستی بسته شد !");
            return RedirectToAction("Index");
        }

        public IActionResult CloseList(int Id)
        {
            var reports = ShopDBContext.Reports.Where(r => r.UserId == int.Parse(User.FindFirst("Id").Value) && r.IsFinally == true).Include(c => c.ReportMessages).Include(r => r.User);
            return View(reports);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Message(int Id, string Body)
        {
            var report = ShopDBContext.Reports.FirstOrDefault(r => r.Id == Id && r.UserId == int.Parse(User.FindFirst("Id").Value));

            if (report == null)
            {
                return RedirectToAction("Index");
            }

            if (report.IsFinally == false)
            {
                ShopDBContext.ReportMessages.Add(new ReportMessage()
                {
                    UserId = int.Parse(User.FindFirst("Id").Value),
                    ReportId = Id,
                    Body = Body,
                });
                ShopDBContext.SaveChanges();
                _toastNotification.Success("پیام فرستاده شد !");
                return RedirectToAction("Show", new
                {
                    Id = Id
                });
            }

            return RedirectToAction("Index");
        }

    }
}

Shop.Web/Areas/User/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shop.Web.Data;
using Shop.Web.Models;
using Shop.Web.Models.ViewModel;

namespace Shop.Web.Areas.User.Controllers
{
    [Area("User")]
    public class ReportController : Controller
    {
        public ShopDBContext ShopDBContext { get; set; }
        public ReportController(ShopDBContext context)
        {
            ShopDBContext = context;
        }
        public IActionResult Index()
        {
            var reports = ShopDBContext.Reports.Where(r => r.UserId == int.Parse(User.FindFirst("Id").Value) && r.IsFinally == false).Include(c => c.ReportMessages).Include(r => r.User);

            return View(reports);
        }

        public IActionResult Report(int Id) {
            var product = ShopDBContext.Products.FirstOrDefault(p => p.Id == Id);
            ShopDBContext.Reports.Add(new Report()
            {
                Title = product.Name,
                Body = ("Product ID : " + product.Id).ToString(),
                IsFinally = false,
                UserId = int.Parse(User.FindFirst("Id").Value)
            });
            ShopDBContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Show(int Id) {
            var report = ShopDBContext.Reports.Include(r => r.ReportMessages).ThenInclude(rm => rm.User).FirstOrDefault(r => r.Id == Id && r.UserId == int.Parse(User.FindFirst("Id").Value));
            if (report == null)
            {
                return NotFound();
            }
            return View(report);
        }

        public IActionResult Close(int Id) {
            var report = ShopDBContext.Reports.FirstOrDefault(r => r.Id == Id);
            if (report == null)
            {
                return NotFound();
            }
            report.IsFinally = true;
            ShopDBContext.Reports.Update(report);
            ShopDBContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult CloseList(int Id) {
            var reports = ShopDBContext.Reports.Where(r => r.UserId == int.Parse(User.FindFirst("Id").Value) && r.IsFinally == true).Include(c => c.ReportMessages).Include(r => r.User);
            return View(reports);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Message(int Id,string Body)
        {
            var report = ShopDBContext.Reports.FirstOrDefault(r => r.Id == Id && r.UserId == int.Parse(User.FindFirst("Id").Value));

            if (report == null)
            {
                return RedirectToAction("Index");
            }

            if (report.IsFinally == false)
            {
                ShopDBContext.ReportMessages.Add(new ReportMessage()
                {
                    UserId = int.Parse(User.FindFirst("Id").Value),
                    ReportId = Id,
                    Body = Body,
                });
                ShopDBContext.SaveChanges();
                return RedirectToAction("Show", new
                {
                    Id = Id
                });
            }
            return RedirectToAction("Index");
        }
    }
}

Shop.Web/Areas/User/Views/Report/Index.cshtml
@model IEnumerable<Report>


<div class="card-body">
    <h1>تمامی گزارش های باز</h1><br/>
    <a asp-controller="Report" asp-action="CloseList" class="btn btn-warning btn-block">
        <i class="nav-icon fa fa-solid fa-bug"></i>
        <p>رفتن به لیست گزارش های بسته شده</p>
    </a><br /><br />
    <hr/>
    <table id="products" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>شماره گزارش</th>
                <th>عنوان</th>
                <th>تعداد چت ها</th>
                <th>عملیات</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var chat in Model)
            {
                <tr>
                    <td>@chat.Id</td>
                    <td>@chat.Title</td>
                    <td>@chat.ReportMessages.Count()</td>
                    <td><div class="btn-group">
                         <a class="btn btn-primary" asp-action="Show" asp-route-id="@chat.Id">رفتن به گزارش</a>
                            <a class="btn btn-danger" asp-action="Close" asp-route-id="@chat.Id">بستن گزارش</a>
                    </div></td>
                </tr>
            }
            @if (Model.Count() == 0)
            {
                <tr>
                    <td>یافت نشد</td>
                    <td>یافت نشد</td>
                    <td>یافت نشد</td>
                    <td>
                    <div class="btn-group">
                        <a class="btn btn-primary disabled">رفتن به گزارش</a>
                        <a class="btn btn-danger disabled">بستن گزارش</a>
                    </div>
                    </td>
                </tr>
            }

        </tbody>
        <tfoot>
            <tr>
                <th>شماره گزارش</th>
                <th>عنوان</th>
                <th>تعداد چت ها</th>
                <th>عملیات</th>
            </tr>
        </tfoot>
    </table>
</div>



@section Scripts{
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables -->
    <script src="~/plugins/datatables/jquery.dataTables.js"></script>
    <script src="~/plugins/datatables/dataTables.bootstrap4.js"></script>
    <!-- SlimScroll -->
    <script src="~/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src=".~/dist/js/demo.js"></script>
    <!-- page script -->
    <script>
        $(function () {
            $("#products").DataTable({
                "language": {
                    "paginate": {
                        "next": "بعدی",
                        "previous": "قبلی"
                    }
                },
                "info": false,
            });
        });
    </script>
}

Shop.Web/Areas/User/Views/Report/Show.cshtml
@model Report


<style>
    .other{
        direction: rtl !important;
        background-color : aqua;
    }
    .myself{
        direction: ltr !important;
        background-color: orange;
    }
</style>



<div class="container mt-2">
    <h1>Report : <span style="color:red">@Model.Title</span></h1>
    <hr/>
    <div>
        <form asp-area="User" asp-controller="Report" asp-action="Message" method="post">
            @Html.AntiForgeryToken()
            <input asp-for="Id" type="number" value="@Model.Id" hidden />
            <input name="Body" type="text" placeholder="لطفا متن را وارد کنید" style="width:100%;padding:20px" /><br /><br />
            <button class="btn btn-primary">ارسال پیام</button>
        </form>
    </div>
    <hr/>

    <div class="column border border-2 p-2" style="width:100%;height:100vh;padding:30px;overflow-y:auto">
        @foreach (var reportMessage in Model.ReportMessages)
        {
            <div class="col-lg-12 p-3 @(reportMessage.UserId != int.Parse(User.FindFirst("Id").Value) ? "other" : "myself")">
                <b><span style="color:@(reportMessage.User.IsAdmin == true ? "red" : "blue")">@(reportMessage.User.IsAdmin == true ? "Admin" : "User")</span>&nbsp; @reportMessage.User.UserName</b>
                <div>
                    <p>
                        @Html.Raw(reportMessage.Body)
                    </p>
                </div>
            </div>
        }
        @*<div class="col-lg-12 myself p-3">
            <b><span style="color:blue">User</span> Mohammad Fathi</b>
            <div>
                <p>
                    hello world
                </p>
            </div>
        </div>*@
    </div>

</div>